build:
  args-dynamic:
    # ---- user ----------------------------------------------------------------
    USER_ID: "$(id -u)"
    GROUP_ID: "$(id -g)"
  args:
    # ---- user ----------------------------------------------------------------
    USER_NAME: "user"
    USER_PASSWORD: "password"
    GRANT_SUDO: "PASSWORDLESS" # PASSWORDLESS, TRUE, or FALSE
    # ---- languages -----------------------------------------------------------
    LANG_C: "FALSE"
    LANG_FORTRAN: "FALSE"
    LANG_PYTHON3: "FALSE"
    LANG_JULIA: "FALSE"
    LANG_R: "FALSE"
    LANG_LATEX: "FALSE"
    # ---- libraries -----------------------------------------------------------
    LIB_MATPLOTLIB : "FALSE"
    LIB_LINALG : "FALSE"
    LIB_OPENMPI: "FALSE"
    LIB_X11: "FALSE"
    # ---- dev enviroment ------------------------------------------------------
    DEV_JUPYTER: "FALSE"
    DEV_THEIA: "FALSE"
    DEV_CLI: "FALSE"
    # ---- additional software -------------------------------------------------
    ASW_SPACK: "FALSE"
    ASW_VNC: "FALSE"
    # ---- additional options --------------------------------------------------
    SHARED_STORAGE_DIR: "/opt/shared" # used to store ~/.julia, ~/.nvm, ~/.npm
environment:
  USE_LOCAL_GIT: "true" # used by theia (https://github.com/eclipse-theia/theia/issues/1964)
  JULIA_DEPOT_PATH: "/opt/shared/julia-depot"
mounts:
  - type: "bind"
    hostPath: "config/jupyter"
    containerPath: "/home/user/.jupyter"
  - type: "bind"
    hostPath: "config/theia"
    containerPath: "/home/user/.theia"
  - type: "bind"
    hostPath: "config/vnc"
    containerPath: "/home/user/.vnc"
  - type: "bind"
    hostPath: "config/vscode"
    containerPath: "/home/user/.vscode"
files:
  containerRoot: "/home/user"
flags:
  podman-userns: keep-id
  docker-chown-file-volume: host-user
  cmd-args: join
  security-opt: "seccomp=unconfined" # added for xfce terminal (see https://github.com/mviereck/x11docker/issues/346).