build:
  args-dynamic:
    # ---- user ----------------------------------------------------------------
    USER_ID: "$(id -u)"
    GROUP_ID: "$(id -g)"
  args:
    # ---- user ----------------------------------------------------------------
    USER_NAME: "user"
    USER_PASSWORD: "password"
    GRANT_SUDO: "PASSWORDLESS" # PASSWORDLESS, TRUE, or FALSE
    # ---- languages -----------------------------------------------------------
    LANG_C: "FALSE"
    LANG_FORTRAN: "FALSE"
    LANG_PYTHON3: "FALSE"
    LANG_JULIA: "FALSE"
    LANG_R: "FALSE"
    LANG_LATEX: "FALSE"
    # ---- libraries -----------------------------------------------------------
    LIB_MATPLOTLIB : "FALSE"
    LIB_LINALG : "FALSE"
    LIB_OPENMPI: "FALSE"
    LIB_X11: "FALSE"
    # ---- dev enviroment ------------------------------------------------------
    DEV_JUPYTER: "FALSE"
    DEV_THEIA: "FALSE"
    DEV_CLI: "FALSE"
    # ---- additional software -------------------------------------------------
    ASW_SPACK: "FALSE"
    ASW_VNC: "FALSE"
environment:
  USE_LOCAL_GIT: "true" # used by theia (https://github.com/eclipse-theia/theia/issues/1964)
mounts:
  - type: "bind"
    hostPath: "config/jupyter"
    containerPath: "/home/user/.jupyter"
  - type: "bind"
    hostPath: "config/theia"
    containerPath: "/home/user/.theia"
files:
  containerRoot: "/home/user"
flags:
  userns: keep-id
  chown-file-volume: host-user
  cmd-args: join